//Autogenerated file, do not manipulate manually
//LocalJsStorage by Edwin Saul https://edwinsaul.com
const LocalJsStorage = {
"lolo": 222
}
console.log(LocalJsStorage);
console.log("hola mundo");
print("lolo");