from os.path import isfile,isdir,join,dirname,abspath

current= dirname(abspath(__file__)) 
currentJS=join(current,"LocalJsStorage/LocalJsStorage.js")
currentPY=join(current,"LocalJsStorage/getJS.py")

js=open(currentJS,"r",encoding="utf8").read().split("\n")
clearJs=[];first=False

#---------------------------------------------

def clearLineJs(line):
    return line

#---------------------------------------------

for x in js:
    if first:
        line=clearLineJs(x)
        if line!="": clearJs.append(x)
    if "//---" in x: first=True

#---------------------------------------------

textJs="\n".join(clearJs)
textPy="# Autogenerated file\n# by Edwin Saul\ndef getJS():\n\treturn \"\"\"\n"+textJs+"\"\"\""

#---------------------------------------------

py=open(currentPY,"w",encoding="utf8")
py.write(textPy)
py.close()

